Repository panditakshay402/HACKTOBERFEST_2024, pull requests merged in 2024-10, with the labels that each got.

#8 selection sort code with comments
  bubbleSort.java
  insertionSort.java
  linearSearch.java
  quickSort.java
  selectionSort.java
Labels: hacktoberfest_accepted, hacktoberfest, hacktoberfest2024

#25 Wine Quality Prediction
  Wine Quality Prediction/Wine_Quality_Prediction.ipynb
  Wine Quality Prediction/Wine_Quality_Predictor_app.py
  Wine Quality Prediction/trained_model.sav
  Wine Quality Prediction/winequality-red.csv
Labels: hacktoberfest_accepted, hacktoberfest

#29 Create Matrix multiplication.cpp
  DSA/Matrix multiplication.cpp
Labels: hacktoberfest_accepted, hacktoberfest

#30 Created python folder and added k means clustering algorithm
  PYTHON/k_means_clustering.py
Labels: hacktoberfest, hacktoberfest-accepted

#31 Added searching algorithms
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  DSA/basic_array_operations.cpp
  DSA/doubly_linked_list.cpp
  DSA/infix_to_postfix.cpp
  DSA/minimum_priority_queue.cpp
  DSA/parenthesis_matching.cpp
  DSA/singly_linked_list.cpp
  DSA/stack_from_2_queues.cpp
  DSA/string_reversal.cpp
  PYTHON/svm.py
  Searching Algo/bfs.py
  Searching Algo/binary_search.py
  Searching Algo/dfs.py
  Searching Algo/linear_search.py
Labels: hacktoberfest, hacktoberfest2024, hacktoberfest-accepted

#34 resolves #13 Radix Sort
  CheatSheet.md
  Sorting Algo/radixSort.java
Labels: hacktoberfest, hacktoberfest2024, hacktoberfest-accepted

#38 Created shopify product image section code
  shopify product image section code
Labels: hacktoberfest, hacktoberfest2024, hacktoberfest-accepted

#37 Create TicTacTo_game
  TicTacTo_game
Labels: hacktoberfest, hacktoberfest2024, hacktoberfest-accepted

#46 add Painter's Partition Problem
  DSA/Painter's Partition Problem
Labels: hacktoberfest, hacktoberfest2024, hacktoberfest-accepted
